name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            actions: write

        steps:          
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Set up JDK 8
            uses: actions/setup-java@v2
            with:
              java-version: '8'
              distribution: 'adopt'

          - name: Install Maven
            run: sudo apt-get update && sudo apt-get install -y maven

          - name: Install Node
            run: |
                curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                sudo apt-get install -y nodejs
     
          - name: Build with Maven
            run: mvn -B package --file my-app/pom.xml

